services:
  tg-bot:
    container_name: "tg-bot-dev"
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    depends_on:
      migrate:
        condition: service_completed_successfully