version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: "tg-bot-db"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5430:5430
    restart: unless-stopped

  pgAdmin:
    container_name: "tg-bot-pg-admin"
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 8081
    ports:
      - 8082:8081
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
